version: '3.8'

services:

  app:
    build: .
    image: ahmed11649/lab8-cicd1:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    restart: unless-stopped

volumes:
  mongo-data: